src/Makefile.am
src/lib.lua
src/lib/getopt.lua

- Add `dnsjit.lib`
- Add `dnsjit.lib.getopt` for handling command arguments
- `dnsjit.core`: Document global variables

Getopt, core documentation

---

examples/Makefile.am
examples/test_throughput.lua
src/Makefile.am
src/input.lua
src/input/pcap.lua
src/input/zero.c
src/input/zero.h
src/input/zero.hh
src/input/zero.lua

- Add `dnsjit.input.zero`, generates empty queries
- Add `example/test_throughput.lua` to use Zero and Null to test throughput
- `input.pcap`: Fix title in documentation

Zero and documentation

---

examples/test_pcap_read.lua

- `examples/test_pcap_read.lua`:
- Add `-l` to test with `filter.layer`
- Add `-t` to test with `filter.thread`
- Fix results when different amount of packets has been read by compared input

Test PCAP read with layer and threads

---

src/core/object/ip.lua
src/core/object/ip6.lua

- `core.object.ip`: Add documentation for padding
- `core.object.ip6`: Add documentation for fragment, routing and padding

Documentation

---

src/core/thread.c
src/core/thread.hh
src/core/thread.lua
src/lib/getopt.lua

- `core.thread`: Can now push strings and integers to the thread's stack
- `lib.getopt`: Sort help output

Getopt and Threads

---

Makefile.am
configure.ac
m4/ax_check_compile_flag.m4
m4/ax_ext.m4
m4/ax_gcc_x86_avx_xgetbv.m4
m4/ax_gcc_x86_cpuid.m4
m4/ax_pthread.m4
m4/dl.sh
src/Makefile.am
src/core/channel.c
src/core/thread.c

- `configure.ac`: Add check for CPU extensions
- `m4`: Add script to download latest m4's
- `core.channel`: Use `ck_ring` correctly
- `core.thread`: Make local function static

CPU extensions and fixes

---

examples/test_throughput.lua
src/core/channel.c
src/core/channel.hh
src/core/channel.lua
src/core/object/ip6.lua

- `examples/test_throughput.lua`: Add tests using `core.thread` and `core.channel`
- `core.channel`:
- Add `receive()` to put objects into the channel
- Add `receiver()` and `run()` to get objects from to channel and pass them to a receiver
- `core.object.ip6`: Make private functions local

Test threads, channels

---

src/core/thread.lua

- `core.thread`:
- Add feature to `push()` multiple values onto stack
- Add feature to `pop()` more then one value of the stack
- Update synopsis

core.thread

---

src/output/respdiff.c
src/output/respdiff.lua

- `output.respdiff`: Add support for timed out responses

Respdiff timeout

---

configure.ac
debian/changelog
rpm/dnsjit.spec
src/dnsjit.1in
src/globals.c

- Add globals for `dnsjit` version and bug report ways
- Alpha v0.9.5

Globals, v0.9.5

---

examples/qr-multi-pcap-state.lua

- `examples/qr-multi-pcap-state.lua`: Add example script to match query with response and save state in order to match across multiple runs

qr multi pcap state

---

src/core/channel.c
src/core/channel.h
src/core/channel.hh
src/core/channel.lua

- added non-blocking `try_put()`
- renamed `size` to `capacity` for consistency with libck
- added function to determine channel size
- added function to determine if channel is full
- fixed validation of channel capacity

core/channel: various improvements

---

src/core/channel.c

See https://github.com/DNS-OARC/dnsjit/pull/123#discussion_r372421506 for details

core/channel: fix core_channel_full() detection

---

src/core/log.c

- Fix compile warnings on 32bit platforms

Compile warnings

---

src/Makefile.am

- Make attributes warnings into errors to ensure support across platforms

attributes

---

src/input/fpcap.c
src/input/mmpcap.c
src/output/dnscli.c
src/output/dnssim/connection.c
src/output/dnssim/tls.c
src/output/tcpcli.c
src/output/udpcli.c

SonarCloud

---

src/lib/ip.lua
src/output/dnssim.c
src/output/dnssim.lua
src/output/dnssim/common.c
src/output/dnssim/udp.c

output/dnssim: add IPv4 support

---

src/output/dnssim/https2.c

The path_len was missing space for terminating null byte.
The output length for base64url_encode() was incorrect, since the space
for terminating null byte was deducted twice - once indirectly with
sizeof(OUTPUT_DNSSIM_HTTP_GET_TEMPLATE) and second time explicitly with
-1.
The regression was introduced in 15a21daf86ebcf6da6599f7b0d66ebc32f76a9fe

output/dnssim: fix regression in DoH GET

---

src/input/fpcap.c
src/input/fpcap.hh
src/input/fpcap.lua
src/input/pcap.lua
src/lib/getopt.lua

(and a related fix in lib.getopt)

Ability to read PCAP from stdin

---

src/output/dnssim.lua
src/output/dnssim/CHANGELOG.md

output/dnssim: add changelog and version checks

---

examples/modules/input-example/Makefile.am
examples/modules/input-example/README.md
examples/modules/input-example/src/Makefile.am
examples/modules/input-example/test.lua

- `input-example`:
- Add dependencies, build and test instructions
- Fix library install path
- Add test

Example input

---

examples/modules/filter-example/Makefile.am
examples/modules/filter-example/README.md
examples/modules/filter-example/autogen.sh
examples/modules/filter-example/configure.ac
examples/modules/filter-example/src/Makefile.am
examples/modules/filter-example/src/filter/counter.c
examples/modules/filter-example/src/filter/counter.lua
examples/modules/filter-example/test.lua
fmt.sh

- Add `example.filter.counter`
- Add code formatting for examples

filter example

---

examples/modules/filter-example/README.md
examples/modules/input-example/README.md
examples/modules/lib-example/Makefile.am
examples/modules/lib-example/README.md
examples/modules/lib-example/autogen.sh
examples/modules/lib-example/configure.ac
examples/modules/lib-example/dnsjit_version.lua
examples/modules/lib-example/src/Makefile.am
examples/modules/lib-example/src/lib/duration.lua
examples/modules/lib-example/test.lua
examples/stand-alone-tool/README.md

- Fix typos in examples READMEs
- Add `example.lib.duration`, a Lua library
- `examples/stand-alone-tool`: Add build/test instructions

example lib

---

src/core/compat.c
src/gen-compat.lua

- Fix #215:
- Generated compat lua code should not include headers
- Incorrect include in compat C code

Fix compat

---

src/output/dnscli.c

- Fix #220: Corrected inline function and made them static, this solves weird LLVM 12+ issue

static inline

---

.gitignore
configure.ac
src/Makefile.am
src/gen-makefile.sh

- Use pkg-config for libpcap and gnutls

pkg-config

---

src/core/thread.c
src/core/thread.h
src/core/thread.hh

- `core.thread`: Issue #233: Fix runtime error, use correct declaration

thread push number

---

.copr/Makefile

- Remove git safe directory workaround

COPR tweaks

---

src/test/test_ipsplit.lua

- Fix #250: handle endian in tests

ipsplit endian
