DNS-OARC/dnsjit

src/Makefile.am
src/gen-manpage.lua
src/lib/parseconf.lua

- Add `dnsjit.lib.parseconf`
- `gen-manpage.lua`
- Use short hand call to string functions
- Fix leak of module name and short description into synopsis
- Verify that synopsis and description works independent
- Fix function display, arguments are normal text

Parseconf and man-page generator

---

README.md
examples/replay.lua
src/dnsjit.1in
src/filter/lua.c
src/filter/roundrobin.c
src/filter/thread.c
src/filter/timing.c
src/input/pcap.c
src/lib.lua
src/lib/getopt.lua
src/lib/parseconf.lua
src/output/cpool.c
src/output/cpool.hh
src/output/cpool.lua
src/output/cpool/client.c
src/output/cpool/client_pool.c
src/output/cpool/client_pool.h

- Fix debug logging, remove `self` pointer output
- `dnsjit.output.cpool`:
- Add SLLQ queue size to `new`, optional value
- Remove static settings, send as UDP and skip replies
- Changed buffers in client shutdown and read
- Add reference to `dnsjit.lib` in README and `dnsjit (1)`
- `dnsjit.lib`: Add reference to `parseconf`
- `dnsjit.lib.getopt` and `dnsjit.lib.parseconf`: Add spacing to synopsis

Logging, cpool and documentation

---

src/Makefile.am
src/core.lua
src/core/query.c
src/core/query.hh
src/core/query.lua
src/core/tracking.c
src/core/tracking.h
src/core/tracking.hh
src/core/tracking.lua
src/input/pcap.c
src/input/pcap.hh

- Fix #6: Add `dnsjit.core.tracking` to track input sources
- `dnsjit.core.query`: Add source id `sid` and query id `qid`
- `dnsjit.input.pcap`: Use `dnsjit.core.tracking` to get a unique source ID for each module instance and keep an own query ID for each query created
- `dnsjit.core.mutex`: Fix include, project headers should be included outside header defines

Source and query tracking

---

examples/dumpdns.lua
examples/filter_rcode.lua
src/core/query.c
src/core/query.lua
src/filter/lua.lua
src/filter/multicopy.lua
src/filter/roundrobin.lua
src/filter/thread.lua
src/filter/timing.lua
src/input/lua.lua
src/input/pcap.lua
src/lib/getopt.lua
src/lib/parseconf.lua
src/output/cpool.lua
src/output/null.lua

- Use same naming of module locals
- `local t_name=""`: the C structure name for the module as string (example `core_log_t`)
- `local <t_name>=...`: the __ctype__ _used_ for creating an object, set either with `ffi.typeof()` or `ffi.metatype()`
- `self.obj`: the C structure if wrapping inside a Lua object
- `core.query`:
- Rework into a pure C structure object, a lot of values are not attributes instead of functions
- Fix bug where DNS header values was not copied

Object naming in modules, query `parse()`

---

src/core/receiver.lua
src/filter/lua.lua
src/filter/thread.lua
src/input/lua.lua
src/lib/getopt.lua
src/lib/parseconf.lua

- Move local variables to the most inner loop they exist in
- Remove reference to `query:struct()`
- `filter.thread`: Use query copy in `send()`

Inner local, query, thread

---

src/core/query.c
src/core/query.hh
src/core/query.lua
src/core/tracking.c
src/core/tracking.hh
src/core/tracking.lua
src/input/pcap.c
src/input/pcap.hh

- Rename Source ID `sid` to `src_id`
- Rename Query ID `qid` to `qr_id`
- `core.tracking`: Add unique thread safe counter for query/response `qr_id` and destination `dst_id`
- `core.query`: Add destination ID

Tracking queries

---

README.md
examples/replay.lua
src/core/query.c
src/core/query.hh
src/filter/timing.c
src/output/cpool.c
src/output/cpool.hh
src/output/cpool.lua
src/output/cpool/client.c
src/output/cpool/client.h
src/output/cpool/client_pool.c
src/output/cpool/client_pool.h

- Update README example for the changes made to `core.query`
- `core.query`:
- CID 263046: Fix buffer overrun in RR label handling
- Add `core_query_copy_addr()` to copy source/destination information from another query
- `filter.timing`:
- CID 260362: Disable last real time, not used
- `output/cpool/client`:
- Add static buffer for non-important reads
- Add `client_set_recvbuf_size()` to allocate a per client receiver buffer
- Add `always_read` option to enable the receiving of data to always be on
- Use `core.tracking` destination ID `dst_id` and set the IDs in the query being processed
- `output/cpool/client_pool`:
- Add `client_recvbuf_size` to set the receive buffer for new clients
- Add `client_always_read` option to set for new clients
- Add `client_pool_client_read_t` callback …

Responses, fixes

---

src/core/query.c
src/core/query.h

- Remove cast in `core_query_raw()` macro
- Fix CID 263048

Core query

---

src/dnsjit.c

- Fix banner when autoconf `PACKAGE_` defines may not exist

Autoheader

---

configure.ac
debian/changelog
rpm/dnsjit.spec
src/core/query.lua

- `core.query`: Fix `log()`, do not attempt to return `_log` since it does not exist anymore
- Bump to v0.9.2

Query Logging, v0.9.2

---

examples/test_throughput.lua
src/filter/thread.c
src/filter/thread.hh
src/filter/thread.lua

- `filter.thread`:
- Add marker for writers so all readers can move to where data will appear
- Add `use_writers()` to control this function
- `examples/test_throughput.lua`: Add option `--thread-writers` to enable writers marker

Thread writers

---

examples/dumpdns-qr.lua

- Add `examples/dumpdns-qr.lua`, an example to dump queries and related responses from a PCAP

Dump DNS query/response

---

.travis.yml
configure.ac
m4/ax_append_flag.m4
m4/ax_cflags_warn_all.m4
m4/ax_require_defined.m4
src/filter/thread.c
src/filter/thread.hh
src/output/cpool/client.c
src/output/cpool/client_pool.c

- `configure`:
- Depend on autoconf v2.64+ for the added macros
- Add `--enable-warn-all` to enable all warnings
- Add `--with-extra-cflags` and `--with-extra-ldflags` to add additional flags without overwriting the default platform flags
- `output.cpool`: Tweak EV usage to workaround GCC warnings

Warn and optimize flags

---

configure.ac
src/core/channel.c

- `configure.ac`: Fix issue on Fedora, ck headers in subdirectory but they themselves include without prefixing `ck/`

Fedora ck includes

---

src/filter/layer.c
src/filter/split.c
src/filter/timing.c
src/filter/timing.h
src/filter/timing.hh
src/filter/timing.lua
src/input/fpcap.c
src/input/mmpcap.c
src/input/pcap.c
src/output/null.c
src/output/respdiff.c
src/output/tcpcli.c
src/output/udpcli.c

- Rework receiver/producer usage
- `filter.timing`:
- Fix display of nanoseconds
- Issue #42: Add producer interface
- Issue #42: Add fixed mode

Timing, receiver/producer

---

src/core/channel.c
src/core/channel.lua
src/core/log.h
src/core/log.hh
src/core/object/dns.hh
src/core/object/ieee802.hh
src/core/object/ip.hh
src/core/object/ip6.hh
src/core/object/pcap.hh
src/input/fpcap.hh
src/input/mmpcap.hh
src/input/pcap.hh

- `core.channel`: Allow sending `nil`
- Remove bit fields, not yet handled by the JIT compiler

Channel, structures

---

configure.ac
debian/changelog
examples/dumpdns-qr.lua
examples/dumpdns.lua
examples/respdiff.lua
rpm/dnsjit.spec
src/output/respdiff.c
src/output/respdiff.hh
src/output/respdiff.lua

- `examples`: Fix check of `transport` and `protocol`
- `output.respdiff`:
- Fix #92: Add option for mapsize (database size)
- Add fatal information if database is full
- Alpha v0.9.6

Respdiff, fixes, v0.9.6

---

src/output/tcpcli.c

- `output.tcpcli`:
- Fix #97: Mark that a new DNS length is needed after getting a full response
- Fix buffer handling if more then one response is received

Fix TCP client

---

README.md
debian/copyright

- Update copyright (missed in previous commit)
- Fix #105: Use FreeBSD package for concurrency kit

Copyright, FreeBSD dependencies

---

configure.ac
examples/replay.lua
examples/replay_multicli.lua
src/Makefile.am
src/core/object/dns.c
src/core/object/dns.h
src/core/object/dns.hh
src/core/object/dns.lua
src/gen-compat.lua
src/gen-makefile.sh
src/output.lua
src/output/dnscli.c
src/output/dnscli.h
src/output/dnscli.hh
src/output/dnscli.lua

- Add `output.dnscli`, a DNS aware UDP/TCP/TLS client
- `examples/replay.lua`: Use `output.dnscli`
- Add `examples/replay_multicli.lua`, example of replay using multiple non-blocking sockets
- `core.object.dns`: Add marker if DNS length is included in the payload (as with TCP)
- `core.compat`: Add `struct pollfd`
- `gen-makefile.sh`: Sort find to minimize changes after each run

output.dnscli

---

src/filter/layer.c

- `filter.layer`: Fix bug in link handler, don't give a pointer of the pointer

Layer pointer pointer

---

src/input/fpcap.c
src/input/fpcap.hh
src/input/fpcap.lua
src/input/mmpcap.c
src/input/mmpcap.hh
src/input/mmpcap.lua

- `input.fpcap`: Fix #109: Add `linktype` and translate `network` to the correct `DLT_`
- `input.mmpcap`: Fix #109: Add `linktype` and translate `network` to the correct `DLT_`

PCAP link type

---

src/filter/timing.c
src/filter/timing.hh
src/filter/timing.lua

The realtime mode is a high-throughput variant of the keep mode. It
is less precise, but is more efficient and able to handle higher
throughput.
If there are significant time gaps in the input packets, the realtime
mode may send them earlier if both packets end up in the same batch.
However, packets are guaranteed to never be sent later than the
specified drift. In cases where the timer isn't able to keep up for any
reason, it aborts the execution.
The default batch size of 128 is an empirical value that has been tested
to perform well with input data of up to ~500k pps.

filter/timing: add realtime mode

---

configure.ac

- Only check for and enable all available CPU extensions if `--enable-cpuext` is used

CPU extensions

---

src/core/object/payload.lua
src/core/object/tcp.lua
src/core/object/udp.lua
src/filter/layer.lua

Sync the documentation to reflect the actual code. Non-existent
attributes were removed from tcp and udp objects. Reference to
payload object carrying the application data was added.

man: update documentation for payload

---

.lgtm.yml
src/Makefile.am
src/gen-makefile.sh
src/output/dnssim.c
src/output/dnssim.hh
src/output/dnssim.lua
src/output/dnssim/common.c
src/output/dnssim/connection.c
src/output/dnssim/internal.h
src/output/dnssim/tcp.c
src/output/dnssim/tls.c

Initial TLS support for dnssim. 
Features:
- can select TLS version and cipher suites with priority strings
- TLS session resumption is also supported and on by default (requires GnuTLS 3.6.3+). It can be explicitly turned off with priority string
Missing features include:
- TLS rehandshake (no plans to implements this)
- TLS false start / early data: this might be useful and might be implemented in the future. Skipped this for now, because it'd be quite complex and I have no use for it at this point
I've done some benchmarks with this and it seems to work (at least in my use-cases).

output/dnssim: add TLS support

---

src/core/log.c

Using stderr for logs makes it possible to utilize stdout for useful
data in dnsjit scripts.

core/log: use stderr for logging

---

src/core/object.lua

I often have to re-write the object chain iteration loop in scripts. It seems such a common operation that I think it makes sense to have it in the object API.
Casting to one of multiple types can also be elegantly done, although at a slightly worse performance:
```
local protocol = obj:cast_to(object.UDP) or obj:cast_to(object.TCP)
```
compared to:
```
local protocol = obj
while protocol ~= nil do
if protocol.obj_type == object.UDP or protocol.obj_type == object.TCP then
break
end
protocol = protocol.obj_prev
end
if protocol ~= nil then
protocol = protocol:cast()
end
```

core/object: add cast_to() method

---

src/core/object/ip.lua
src/core/object/ip6.lua

It's useful to be able to convert IP from byte array to string representation without having any actual ip/ip6 object, e.g.:
```
local ip6 = require("dnsjit.core.object.ip6")
-- node.key is uint8_t[16] cdata
print(ip6.tostring(node.key, true))
```

core/object/ip+ip6: allow string conversion to be used without object

---

src/output/dnssim/common.c
src/output/dnssim/connection.c
src/output/dnssim/internal.h
src/output/dnssim/udp.c

This has some performance impact, but not significant enough to warrant further optimizations at this point.

output/dnssim: match QUESTION section of received responses

---

src/output/dnssim/connection.c
src/output/dnssim/https2.c
src/output/dnssim/internal.h
src/output/dnssim/tls.c

Allow receiving of data when connection is marked as CONGESTED,
which is used by HTTP layer to indicate another connection should be
opened instead of re-using this one for new queries.

output/dnssim: fix handling CONGESTED and closing connections

---

src/output/dnssim.c
src/output/dnssim.lua

Using udp() and selecting whether TCP fallback is performed
with an argument seems to be a cleaner API.
Deprecate udp_only() method which is now basically a duplicate of
calling udp(). udp_only() should be removed in dnsjit 2.0.
Related #173, #159

output/dnssim: implement udp(tcp_fallback) method

---

src/output/dnssim.c
src/output/dnssim.hh
src/output/dnssim.lua

It's useful if the user can customize the instance log name for dnssim,
especially since the component typically has multiple instances than can
be configured differently.

output/dnssim: allow user-set instance log name

---

src/filter/ipsplit.c
src/test/test_ipsplit.lua

The new implementation is the same as glibc's rand(). Now maximum random
numbers can be up to 2^31 -1, compared to the previous max of 2^15 - 1.

filter/ipsplit: extend PRNG modulus to 2^31

---

src/output/pcap.c
src/output/pcap.hh
src/output/pcap.lua

- `output/pcap`:
- Update `open()` man-page, indicate usage of `pcap_dump_open()`
- Add `have_errors()` to check for write errors during/after dumping

Output PCAP man-page, errors

---

examples/stand-alone-tool/src/test/Makefile.am

- `examples/stand-alone-tool`: Fix variable quoting when creating `env.sh`

Stand-alone tool example

---

README.md
examples/capture.lua
examples/dumpdns-qr.lua
examples/dumpdns.lua
examples/dumpdns2pcap.lua
examples/filter_rcode.lua
examples/qr-multi-pcap-state.lua
examples/readme.lua
examples/replay.lua
examples/replay_multicli.lua
examples/respdiff.lua
src/core/object/dns.c
src/core/object/dns.hh
src/core/object/dns.lua

- `core.object.dns`: Add `reset()` to reset the object so it can be reused correctly
- `examples`:
- Add usage of DNS object reset
- Fix handling of TCP payload when it includes the DNS length

DNS reset, dnslen TCP

---

src/core/channel.hh
src/core/thread.c
src/core/thread.h
src/core/thread.hh
src/core/thread.lua

- `core.thread`: Fix #233: Replace `core_thread_push_int64()` with `core_thread_push_number()` and use `lua_Number` instead of `int64_t` to actually push/pop numbers

thread push number

---

src/input/zmmpcap.c

- `input.zmmpcap`: Fix incorrect check of available bytes for gzip/lzma streams

Fix zzmpcap

---

src/lib/trie.c

This should resolve https://sonarcloud.io/project/issues?open=AYw_KgZGcvK1YDgPXu_c&id=dns-oarc%3Adnsjit
Taken from https://gitlab.nic.cz/knot/knot-resolver/-/commit/c1bdcd06cb20948971c0110e6f28a4254828ea23

Fix a potential memory leak in trie

---

src/filter/layer.c

- `filter.layer`: Fix #252: correct UDP padding calculation

UDP padding
